spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/something
    username: something
    password: something

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379

  cache:
    redis:
      time-to-live: 1h

  data:
    redis:
      repositories:
        enabled: true

server:
  port: 1488